---
version: "2.4"

volumes:
  noc_custom:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/noc/custom
      o: bind
      type: bind
  noc_code:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/noc/code
      o: bind
      type: bind
  noc_beef:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/noc/beef
      o: bind
      type: bind
  noc_tmp:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/noc/tmp
      o: bind
      type: bind


services:
  shell:
    image: registry.getnoc.com/noc/noc/dev:$NOC_VERSION_TAG
    restart: "no"
    # volumes:
    #   - /Users/dv/Projects/noc-collections/src:/opt/noc/collections
    working_dir: /opt/noc
    command: /usr/bin/ipython
    env_file:
      - ./data/noc/etc/noc.conf
    volumes:
      - noc_custom:/opt/noc_custom:ro
      - noc_code:/$NOC_CODE_PATH:ro
      - noc_beef:/var/lib/noc/beef
      - noc_tmp:/tmp/noc
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      traefik.enable: false
